trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install && npm run client-install
  displayName: 'Install project dependencies'

- script: |
    # Download and install the latest Snyk CLI
    curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
    chmod +x snyk
    sudo mv snyk /usr/local/bin/

    # Install snyk-to-html globally for converting the results to HTML
    npm install -g snyk-to-html

    # Create the results directory before outputting files
    mkdir -p results

    # Authenticate using the token from pipeline secrets
    snyk auth $SNYK_TOKEN

    # Run Snyk OSS test, output JSON results (including all projects)
    snyk test --all-projects --json-file-output=results/oss.json --debug

    # Run Snyk Code test, output SARIF results
    snyk code test --sarif > results/sast.sarif --debug

    # Convert JSON and SARIF results to HTML
    snyk-to-html -o results/oss.html < results/oss.json
    snyk-to-html -o results/sast.html < results/sast.sarif
  env:
    SNYK_TOKEN: $(SNYK_TOKEN)
  displayName: 'Run Snyk security scans and generate reports'

- publish: $(System.DefaultWorkingDirectory)/results
  artifact: results
  displayName: 'Publish Snyk results as artifact'
